<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) :?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()) :?>
        <div class="field qty">
            <!--<label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label> -->
            <div class="control">
                <input type="hidden"
                       name="qty"
                       id="qty"
                       min="0"
                       value="<?= $block->getProductDefaultQty() * 1 ?>"
                       title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                    class="action primary tocart"
                    id="product-addtocart-button" disabled>
                <span><?= $block->escapeHtml($buttonTitle) ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>

<script>
    require([
        'jquery'
    ], function ($) {
        $(document).ready(function () {
            $('#product-addtocart-button').click(function (event) {
                var purchaseUnit = parseInt($('#purchase-unit').val());

                if (!isNaN(purchaseUnit) && purchaseUnit > 0) {
                    var valid = true;
                    $('.row_total').each(function () {
                        var rowTotal = parseInt($(this).text().trim());

                        if (rowTotal !== 0 && rowTotal % purchaseUnit !== 0) {
                            alert('Este producto se vende en múltiplos de ' + purchaseUnit);
                            valid = false;
                            return false; // Termina el recorrido por los elementos
                        }
                    });

                    if (!valid) {
                        event.preventDefault(); // Previene la ejecución del submit
                    }
                }
            });
        });
    });
</script>
