<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var $block \Magento\Sales\Block\Order\Recent */
?>
<div class="block block-dashboard-orders">
    <?php
    $_orders = $block->getOrders();
    $count = count($_orders);
    ?>
    <div class="block-title order">
        <strong><?= $block->escapeHtml(__('Recent Orders')) ?></strong>
        <?php if ($count > 0) : ?>
            <a class="action view" href="<?= $block->escapeUrl($block->getUrl('sales/order/history')) ?>">
                <span><?= $block->escapeHtml(__('View All')) ?></span>
            </a>
        <?php endif; ?>
    </div>
    <div class="block-content">
        <?= $block->getChildHtml() ?>
        <?php if ($count > 0) : ?>
            <div class="table-wrapper orders-recent">
                <table class="data table table-order-items recent" id="my-orders-table">
                    <caption class="table-caption"><?= $block->escapeHtml(__('Recent Orders')) ?></caption>
                    <thead>
                    <tr>
                        <th scope="col" class="col id"><?= $block->escapeHtml(__('Order #')) ?></th>
                        <th scope="col" class="col date"><?= $block->escapeHtml(__('Date')) ?></th>
                        <th scope="col" class="col shipping"><?= $block->escapeHtml(__('Ship To')) ?></th>
                        <th scope="col" class="col total"><?= $block->escapeHtml(__('Order Total')) ?></th>
                        <th scope="col" class="col status"><?= $block->escapeHtml(__('Status')) ?></th>
                        <th scope="col" class="col Address"><?= $block->escapeHtml(__('Address')) ?></th>
                        <th scope="col" class="col actions"><?= $block->escapeHtml(__('Action')) ?></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($_orders as $_order) : ?>
                        <tr>
                            <td data-th="<?= $block->escapeHtml(__('Order #')) ?>" class="col id"><?= $block->escapeHtml($_order->getRealOrderId()) ?></td>
                            <td data-th="<?= $block->escapeHtml(__('Date')) ?>" class="col date"><?= $block->escapeHtml($block->formatDate($_order->getCreatedAt())) ?></td>
                            <td data-th="<?= $block->escapeHtml(__('Ship To')) ?>" class="col shipping"><?= $_order->getShippingAddress() ? $block->escapeHtml($_order->getShippingAddress()->getName()) : "&nbsp;" ?></td>
                            <td data-th="<?= $block->escapeHtml(__('Order Total')) ?>" class="col total"><?= /* @noEscape */ $_order->formatPrice($_order->getGrandTotal()) ?></td>
                            <td data-th="<?= $block->escapeHtml(__('Status')) ?>" class="col status"><?= $block->escapeHtml($_order->getStatusLabel()) ?></td>
                            <?php
                                $shippingAddress = $_order->getShippingAddress();
                                if ($shippingAddress !== null) {
                                    $address = '';
//                                    $region = $shippingAddress->getRegion() ?? '';
//                                    $city = $shippingAddress->getCity() ?? '';
                                    $street = $shippingAddress->getStreet();
                                    $street1 = $street[0] ?? '';
                                    $street2 = $street[1] ?? '';

//                                    $address .= $block->escapeHtml($region . ', ');
//                                    $address .= $block->escapeHtml($city . ', ');
                                    $address .= $block->escapeHtml($street1 . ' ');
                                    $address .= $block->escapeHtml($street2);

                                    // Limitar la longitud de la dirección a 50 caracteres
                                    $address = mb_substr($address, 0, 80);
                                } else {
                                    $address = '';
                                }
                                ?>
                            <td data-th="<?= $block->escapeHtml(__('Address')) ?>" class="col shipping"><?= $block->escapeHtml($address) ?></td>
                            <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
                                <a href="<?= $block->escapeUrl($block->getViewUrl($_order)) ?>" class="action view">
                                    <span><?= $block->escapeHtml(__('View Order')) ?></span>
                                </a>
                                <?php
                                // Verificar si la orden es de los últimos 14 días para permitir el reorder
                                $canReorder = strtotime($_order->getCreatedAt()) >= strtotime('-14 days');
                                if ($canReorder ) :
                             //       $postData = $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)->getPostData($block->getReorderUrl($_order));
                                    ?>
                                    <a href="#" data-order-id="<?= $_order->getEntityId() ?>" class="action reorder">
                                        <span><?= $block->escapeHtml(__('Reorder')) ?></span>
                                    </a>
                                <?php endif ?>

                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        <?php else : ?>
            <div class="message info empty"><span><?= $block->escapeHtml(__('You have placed no orders.')) ?></span></div>
        <?php endif; ?>
    </div>
</div>

<script type="application/javascript">
    require(['jquery', 'ko', 'uiRegistry'],
        function ($, ko, registry) {
            $('.reorder').on('click', function (e) {
                e.preventDefault();

                var orderId = $(this).data('order-id');

                $('body').trigger('processStart');

                setTimeout(function () {
                    $.ajax({
                        url: '<?= $block->getUrl("sales/order/reorder") ?>order_id/' + orderId,
                        type: 'POST',
                        async: false,
                        success: function () {
                            window.location.href = '<?= $block->getUrl("checkout/cart/index") ?>';
                        },
                        error: function (xhr, status, error) {
                            console.error("Error al realizar reorder:", error);
                        },
                        complete: function () {
                            setTimeout(function () {
                                $('body').trigger('processStop')
                            }, 2000);
                        }
                    });
                }, 500);
            });
        }
    );
</script>
