<?php
namespace Southbay\ImportCustomers\Console\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Magento\Framework\App\State;
use Magento\Framework\App\Area;
use Magento\Customer\Model\CustomerFactory;
use Magento\Store\Model\StoreManagerInterface;
use Southbay\CustomCustomer\Model\CustomerConfigFactory;
use Southbay\CustomCustomer\Model\ResourceModel\SoldTo\CollectionFactory as SoldToCollectionFactory;
use Magento\Customer\Api\CustomerRepositoryInterface;
use Magento\Framework\Encryption\EncryptorInterface;

/**
 * Command to import customers from predefined data.
 */
class ImportCustomers extends Command
{
    /**
     * @var State
     */
    protected $state;

    /**
     * @var CustomerFactory
     */
    protected $customerFactory;

    /**
     * @var StoreManagerInterface
     */
    protected $storeManager;

    /**
     * @var CustomerConfigFactory
     */
    protected $customerConfigFactory;

    /**
     * @var SoldToCollectionFactory
     */
    protected $soldToCollectionFactory;

    /**
     * @var CustomerRepositoryInterface
     */
    protected $customerRepository;

    /**
     * @var EncryptorInterface
     */
    protected $encryptor;
    /**
     * ImportCustomers constructor.
     *
     * @param State $state
     * @param CustomerFactory $customerFactory
     * @param StoreManagerInterface $storeManager
     * @param CustomerConfigFactory $customerConfigFactory
     * @param SoldToCollectionFactory $soldToCollectionFactory
     * @param CustomerRepositoryInterface $customerRepository
     * @param EncryptorInterface $encryptor
     */
    public function __construct(
        State $state,
        CustomerFactory $customerFactory,
        StoreManagerInterface $storeManager,
        CustomerConfigFactory $customerConfigFactory,
        SoldToCollectionFactory $soldToCollectionFactory,
        CustomerRepositoryInterface $customerRepository,
        EncryptorInterface $encryptor

    ) {
        $this->state = $state;
        $this->customerFactory = $customerFactory;
        $this->storeManager = $storeManager;
        $this->customerConfigFactory = $customerConfigFactory;
        $this->soldToCollectionFactory = $soldToCollectionFactory;
        $this->customerRepository = $customerRepository;
        $this->encryptor = $encryptor;
        parent::__construct();
    }

    /**
     * Configures the current command.
     */
    protected function configure()
    {
        $this->setName('southbay:customers:import1')
            ->setDescription('Import users from predefined data');
    }

    /**
     * Executes the current command.
     *
     * @param InputInterface $input
     * @param OutputInterface $output
     * @return int
     */
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $this->state->setAreaCode(Area::AREA_ADMINHTML);
        $userData =$this->groupDataperMail();  ;
        foreach ($userData as $userDataItem) {
            $userEmail = $userDataItem['MAIL'];
            if (empty($userEmail)) {
                break;
            }
            if (empty($userDataItem['NOMBRE'])) {
                $userName = $userDataItem['NOMBRE_CLIENTE'];
                $userLastName = $userDataItem['NOMBRE_CLIENTE'];
            } else {
                $userName = $userDataItem['NOMBRE'];
                $userLastName = $userDataItem['APELLIDO'];
            }

            // Create customer
            $customer = $this->customerFactory->create();
            $customer->setWebsiteId(1);
            $customer->setEmail($userEmail);
            $customer->setFirstname($userName);
            $customer->setLastname($userLastName);
            $password = 'southbay2024';
           // $customer->setPassword($this->encryptor->getHash($password)); // Encrypt the password
             $customer->setPassword($password); // Encrypt the password

            try {
                $customer->save();
                $country = 'AR';
                if ($userDataItem['pais'] == 'URU'){
                    $country = 'UY';
                }
                $soCodes = explode(',', $userDataItem['SO']);

                $collection = $this->soldToCollectionFactory->create()->addFieldToFilter('southbay_sold_to_customer_code', ['in' => $soCodes]);
                $soldsToArray = [];

                foreach ($collection as $item) {
                    $soldsToArray[] =   $item->getId();
                }
                $soldsToString= implode(',', $soldsToArray);
                $customerConfig = $this->customerConfigFactory->create();
                $customerConfig->setMagentoCustomerEmail($userEmail);
                $customerConfig->setSoldToIds($soldsToString);
                $customerConfig->setCountriesCodes($country);
                $customerConfig->setFunctionsCodes('rtv,futures');

                $customerConfig->save();

                $output->writeln('<info>Customer and CustomerConfig entry created successfully for customer: ' . $userEmail . '</info>');
            } catch (\Exception $e) {
                $output->writeln('<error>Failed to create customer: ' . $userEmail . '</error>');
                $output->writeln('<error>' . $e->getMessage() . '</error>');
            }
        }

        $output->writeln('<info>Users imported successfully.</info>');
        return 1;
    }

    public function groupDataperMail(){
        $userData= $this->getData();
        $groupedUserData = [];
        foreach ($userData as $userDataItem) {
            $userEmail = $userDataItem['MAIL'];
            $userSO = $userDataItem['SO'];

            // Verificar si el correo electrónico está vacío
            if (empty($userEmail)) {
                continue;
            }
            // Verificar si el correo electrónico ya existe en el array agrupado
            if (isset($groupedUserData[$userEmail])) {
                // Si ya existe, concatenar el valor SO al valor existente en el array agrupado
                $groupedUserData[$userEmail]['SO'] .= ',' . $userSO;
            } else {
                // Si es el primer registro para este correo electrónico, mantener los valores existentes y establecer SO
                $groupedUserData[$userEmail] = $userDataItem;
            }
        }
            return $groupedUserData;
    }



    public function getData(){
        $data =
        [
            22 => [
                'MAIL' => 'fercaste@vera.com.uy',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'ALCOIANO SRL',
                'SO' => '1400000002',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            23 => [
                'MAIL' => 'alcoiano.info@gmail.com',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'ALCOIANO SRL',
                'SO' => '1400000002',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            24 => [
                'MAIL' => 'goncalves.nestor@gmail.com',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'JUAN GONCALVES Y CIA.SRL',
                'SO' => '1400000004',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            25 => [
                'MAIL' => 'dariostar.sergiogarcia@gmail.com',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'DARIOSTAR S.A.',
                'SO' => '1400000006',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            26 => [
                'MAIL' => 'dariostar.nataliarodriguez@gmail.com',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'DARIOSTAR S.A.',
                'SO' => '1400000006',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            27 => [
                'MAIL' => 'dariostar.fabianabentancor@gmail.com',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'DARIOSTAR S.A.',
                'SO' => '1400000006',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            28 => [
                'MAIL' => 'sebastianruiz@wandamel.com',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'WANDAMEL S.A.',
                'SO' => '1400000007',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            29 => [
                'MAIL' => 'nancyadministracion@wandamel.com',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'WANDAMEL S.A.',
                'SO' => '1400000007',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            30 => [
                'MAIL' => 'yolanda@wandamel.com',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'WANDAMEL S.A.',
                'SO' => '1400000007',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            31 => [
                'MAIL' => 'aldo.aiub@falarsa.com',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'FALAR S.A.',
                'SO' => '1400000008',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            32 => [
                'MAIL' => 'atencionalcliente@falarsa.com',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'FALAR S.A.',
                'SO' => '1400000008',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            33 => [
                'MAIL' => 'duvalblanco@icloud.com',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'RICKISLAND S.A.',
                'SO' => '1400000010',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            34 => [
                'MAIL' => 'emiliano@macri.com.uy',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'MARIO C. MACRI S.A.',
                'SO' => '1400000011',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            35 => [
                'MAIL' => 'isabel.nievas@macri.com.uy',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'MARIO C. MACRI S.A.',
                'SO' => '1400000011',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            36 => [
                'MAIL' => 'silvana.defaccio@macri.com.uy',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'MARIO C. MACRI S.A.',
                'SO' => '1400000011',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            37 => [
                'MAIL' => 'lisandro@macri.com.uy',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'STARMAC S.A',
                'SO' => '1400000012',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            38 => [
                'MAIL' => 'analy.perez@macri.com.uy',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'STARMAC S.A',
                'SO' => '1400000012',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            39 => [
                'MAIL' => 'alejandra.ferreira@macri.com.uy',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'STARMAC S.A',
                'SO' => '1400000012',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            40 => [
                'MAIL' => 'carol.mello@macri.uy',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'STARMAC S.A',
                'SO' => '1400000012',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            41 => [
                'MAIL' => 'mmmendezp@gmail.com',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'MENPI S.A.',
                'SO' => '1400000016',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            42 => [
                'MAIL' => 'lorena.menpi@gmail.com',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'MENPI S.A.',
                'SO' => '1400000016',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            43 => [
                'MAIL' => 'andrea.menpi@gmail.com',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'MENPI S.A.',
                'SO' => '1400000016',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            44 => [
                'MAIL' => 'mazzizssj4@hotmail.com',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'LANIBAN S.A.',
                'SO' => '1400000017',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            45 => [
                'MAIL' => 'robertlatalladatito@gmail.com',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'LANIBAN S.A.',
                'SO' => '1400000017',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            46 => [
                'MAIL' => 'casafermar@adinet.com.uy',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'LANIBAN S.A.',
                'SO' => '1400000017',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            47 => [
                'MAIL' => 'robertoboero@gmail.com',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'LABIGOLD S.A.',
                'SO' => '1400000018',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            48 => [
                'MAIL' => 'labigold.deposito@gmail.com',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'LABIGOLD S.A.',
                'SO' => '1400000018',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            49 => [
                'MAIL' => 'labigold.alinson@gmail.com',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'LABIGOLD S.A.',
                'SO' => '1400000018',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            50 => [
                'MAIL' => 'adriangiannotti@hotmail.com',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'LIDERBLEX SA',
                'SO' => '1400000020',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            51 => [
                'MAIL' => 'logistica@giannotti.com.uy',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'LIDERBLEX SA',
                'SO' => '1400000020',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            52 => [
                'MAIL' => 'monacodeportes@hotmail.com',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'HOFLAND S.A.',
                'SO' => '1400000021',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            53 => [
                'MAIL' => 'monacodeportes@hotmail.com',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'ATLHETIC SRL',
                'SO' => '1400000023',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            54 => [
                'MAIL' => 'monacodeportes@hotmail.com',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'MONACO SRL',
                'SO' => '1400000003',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            55 => [
                'MAIL' => 'monacotbo@gmail.com',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'HOFLAND S.A.',
                'SO' => '1400000021',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            56 => [
                'MAIL' => 'monacotbo@gmail.com',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'ATLHETIC SRL',
                'SO' => '1400000023',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            57 => [
                'MAIL' => 'monacotbo@gmail.com',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'MONACO SRL',
                'SO' => '1400000003',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            58 => [
                'MAIL' => 'soledadezquerra@gmail.com',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'HOFLAND S.A.',
                'SO' => '1400000021',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            59 => [
                'MAIL' => 'soledadezquerra@gmail.com',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'ATLHETIC SRL',
                'SO' => '1400000023',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            60 => [
                'MAIL' => 'soledadezquerra@gmail.com',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'MONACO SRL',
                'SO' => '1400000003',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            61 => [
                'MAIL' => 'luislagioia@gmail.com',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'GOAL SPORT S.A',
                'SO' => '1400000022',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            62 => [
                'MAIL' => 'corner.sport@hotmail.com',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'GOAL SPORT S.A',
                'SO' => '1400000022',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            63 => [
                'MAIL' => 'producto@sportline.com.uy',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'NSP',
                'SO' => '1400000435',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            64 => [
                'MAIL' => 'producto@sportline.com.uy',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'MULTIBRAND',
                'SO' => '1400000436',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            65 => [
                'MAIL' => 'administracion1@eltonir.com.uy',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'MULTIBRAND',
                'SO' => '1400000436',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            66 => [
                'MAIL' => 'administracion1@eltonir.com.uy',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'GLOBAL',
                'SO' => '1400000437',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            67 => [
                'MAIL' => 'administracion1@eltonir.com.uy',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'ZOOKO',
                'SO' => '1400000438',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            68 => [
                'MAIL' => 'administracion1@eltonir.com.uy',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'MILBUS SA',
                'SO' => '1400000015',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            69 => [
                'MAIL' => 'sports@adinet.com.uy',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'GLOBAL',
                'SO' => '1400000437',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            70 => [
                'MAIL' => 'sports@adinet.com.uy',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'ZOOKO',
                'SO' => '1400000438',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            71 => [
                'MAIL' => 'sports@adinet.com.uy',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'MILBUS SA',
                'SO' => '1400000015',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            72 => [
                'MAIL' => 'estanislao.pinero@southbay.com.ar',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'NDDC',
                'SO' => '1400000441',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            73 => [
                'MAIL' => 'sebastian.fernandez@southbay.com.ar',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'NDDC',
                'SO' => '1400000441',
                'PAIS' => 'URU',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            74 => [
                'MAIL' => 'ymedina@grupodabra.com.ar',
                'NOMBRE' => 'Yesica',
                'APELLIDO' => 'Medina',
                'NOMBRE_CLIENTE' => 'DABRA S.A.',
                'SO' => '1400000027',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            75 => [
                'MAIL' => 'ymedina@grupodabra.com.ar',
                'NOMBRE' => 'Yesica',
                'APELLIDO' => 'Medina',
                'NOMBRE_CLIENTE' => 'MOOV',
                'SO' => '1400000141',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            76 => [
                'MAIL' => 'ymedina@grupodabra.com.ar',
                'NOMBRE' => 'Yesica',
                'APELLIDO' => 'Medina',
                'NOMBRE_CLIENTE' => 'DEXTER',
                'SO' => '1400000142',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            77 => [
                'MAIL' => 'ymedina@grupodabra.com.ar',
                'NOMBRE' => 'Yesica',
                'APELLIDO' => 'Medina',
                'NOMBRE_CLIENTE' => 'STOCKCENTER',
                'SO' => '1400000143',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            78 => [
                'MAIL' => 'mrestivo@grupodabra.com.ar',
                'NOMBRE' => 'Maria Andrea',
                'APELLIDO' => 'Restivo',
                'NOMBRE_CLIENTE' => 'DABRA S.A.',
                'SO' => '1400000027',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            79 => [
                'MAIL' => 'mrestivo@grupodabra.com.ar',
                'NOMBRE' => 'Maria Andrea',
                'APELLIDO' => 'Restivo',
                'NOMBRE_CLIENTE' => 'MOOV',
                'SO' => '1400000141',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            80 => [
                'MAIL' => 'mrestivo@grupodabra.com.ar',
                'NOMBRE' => 'Maria Andrea',
                'APELLIDO' => 'Restivo',
                'NOMBRE_CLIENTE' => 'DEXTER',
                'SO' => '1400000142',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            81 => [
                'MAIL' => 'mrestivo@grupodabra.com.ar',
                'NOMBRE' => 'Maria Andrea',
                'APELLIDO' => 'Restivo',
                'NOMBRE_CLIENTE' => 'STOCKCENTER',
                'SO' => '1400000143',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            82 => [
                'MAIL' => 'depositodefallas2011@hotmail.com',
                'NOMBRE' => 'Marcos',
                'APELLIDO' => 'Medina',
                'NOMBRE_CLIENTE' => 'CAMARINAS S.A.',
                'SO' => '1400000119',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            83 => [
                'MAIL' => 'depositodefallas2011@hotmail.com',
                'NOMBRE' => 'Marcos',
                'APELLIDO' => 'Medina',
                'NOMBRE_CLIENTE' => 'VIMIANZO S.A.',
                'SO' => '1400000125',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            84 => [
                'MAIL' => 'depositodefallas2011@hotmail.com',
                'NOMBRE' => 'Marcos',
                'APELLIDO' => 'Medina',
                'NOMBRE_CLIENTE' => 'FITZROVIA',
                'SO' => '1400000189',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            85 => [
                'MAIL' => 'depositodefallas2011@hotmail.com',
                'NOMBRE' => 'Marcos',
                'APELLIDO' => 'Medina',
                'NOMBRE_CLIENTE' => 'LORIA 2',
                'SO' => '1400000190',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            86 => [
                'MAIL' => 'robertobustos@vaypol.com.ar',
                'NOMBRE' => 'Roberto',
                'APELLIDO' => 'Bustos',
                'NOMBRE_CLIENTE' => 'MABEL SALINAS S.A.',
                'SO' => '1400000120',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            87 => [
                'MAIL' => 'robertobustos@vaypol.com.ar',
                'NOMBRE' => 'Roberto',
                'APELLIDO' => 'Bustos',
                'NOMBRE_CLIENTE' => 'MABEL SALINAS BETTER SG 2.0 SAN MAR',
                'SO' => '1400000191',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            88 => [
                'MAIL' => 'robertobustos@vaypol.com.ar',
                'NOMBRE' => 'Roberto',
                'APELLIDO' => 'Bustos',
                'NOMBRE_CLIENTE' => 'MABEL SALINAS C. S. NSW',
                'SO' => '1400000192',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            89 => [
                'MAIL' => 'Garantias@dash-deportes.com.ar',
                'NOMBRE' => 'Pablo',
                'APELLIDO' => 'Velardez',
                'NOMBRE_CLIENTE' => 'ANNEX S.A.',
                'SO' => '1400000126',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            90 => [
                'MAIL' => 'Devoluciones@ferreirasport.com',
                'NOMBRE' => 'Marcela',
                'APELLIDO' => 'Sevalt',
                'NOMBRE_CLIENTE' => 'FERREIRA SEPTIMO',
                'SO' => '1400000148',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            91 => [
                'MAIL' => 'Devoluciones@ferreirasport.com',
                'NOMBRE' => 'Marcela',
                'APELLIDO' => 'Sevalt',
                'NOMBRE_CLIENTE' => 'FERREIRA SPORT S.A',
                'SO' => '1400000128',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            92 => [
                'MAIL' => 'devoluciones@sevensportgroup.com.ar',
                'NOMBRE' => 'Ezequiel',
                'APELLIDO' => 'Vazquez',
                'NOMBRE_CLIENTE' => 'FACTORY SPORT S.A.',
                'SO' => '1400000129',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            93 => [
                'MAIL' => 'devoluciones@sevensportgroup.com.ar',
                'NOMBRE' => 'Ezequiel',
                'APELLIDO' => 'Vazquez',
                'NOMBRE_CLIENTE' => 'TOP SPORT S.A',
                'SO' => '1400000130',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            94 => [
                'MAIL' => 'devoluciones@sevensportgroup.com.ar',
                'NOMBRE' => 'Ezequiel',
                'APELLIDO' => 'Vazquez',
                'NOMBRE_CLIENTE' => 'FORTALEZA EXTREMA S.A.',
                'SO' => '1400000131',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            95 => [
                'MAIL' => 'devoluciones@sevensportgroup.com.ar',
                'NOMBRE' => 'Ezequiel',
                'APELLIDO' => 'Vazquez',
                'NOMBRE_CLIENTE' => 'FACTORY BETTER',
                'SO' => '1400000153',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            96 => [
                'MAIL' => 'devoluciones@sevensportgroup.com.ar',
                'NOMBRE' => 'Ezequiel',
                'APELLIDO' => 'Vazquez',
                'NOMBRE_CLIENTE' => 'FORTALEZ EXTREMA S.A CHELSEA',
                'SO' => '1400000204',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            97 => [
                'MAIL' => 'rodrigo.chazarreta@lacelada.com',
                'NOMBRE' => 'Rodrigo',
                'APELLIDO' => 'Chazarreta',
                'NOMBRE_CLIENTE' => 'LA CELADA JJ DEPORTES',
                'SO' => '1400000132',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            98 => [
                'MAIL' => 'rodrigo.chazarreta@lacelada.com',
                'NOMBRE' => 'Rodrigo',
                'APELLIDO' => 'Chazarreta',
                'NOMBRE_CLIENTE' => 'LA CELADA ON SPORTS',
                'SO' => '1400000154',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            99 => [
                'MAIL' => 'rodrigo.chazarreta@lacelada.com',
                'NOMBRE' => 'Rodrigo',
                'APELLIDO' => 'Chazarreta',
                'NOMBRE_CLIENTE' => 'LA CELADA IN STORE',
                'SO' => '1400000155',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            100 => [
                'MAIL' => 'deposito@totalsport.com.ar',
                'NOMBRE' => 'Diego',
                'APELLIDO' => 'Rodriguez',
                'NOMBRE_CLIENTE' => 'TOTAL SPORT SRL',
                'SO' => '1400000133',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            101 => [
                'MAIL' => 'yrodriguez@coppel.com.ar',
                'NOMBRE' => 'Yesica',
                'APELLIDO' => 'Rodriguez',
                'NOMBRE_CLIENTE' => 'COPPEL S.A.',
                'SO' => '1400000134',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            102 => [
                'MAIL' => 'blopez@coppel.com.ar',
                'NOMBRE' => 'Blacida',
                'APELLIDO' => 'Lopez',
                'NOMBRE_CLIENTE' => 'COPPEL S.A.',
                'SO' => '1400000134',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            103 => [
                'MAIL' => 'forsaria@coppel.com.ar',
                'NOMBRE' => 'Franco',
                'APELLIDO' => 'Orsaria',
                'NOMBRE_CLIENTE' => 'COPPEL S.A.',
                'SO' => '1400000134',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            104 => [
                'MAIL' => 'Julieta.ramirez@woodooskateboards.com',
                'NOMBRE' => 'Julieta',
                'APELLIDO' => 'Ramirez',
                'NOMBRE_CLIENTE' => 'DRIFTER S.A.',
                'SO' => '1400000135',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            105 => [
                'MAIL' => 'compostura@opensports.com.ar',
                'NOMBRE' => 'Pablo',
                'APELLIDO' => 'Damianovich',
                'NOMBRE_CLIENTE' => 'MDQ R&B',
                'SO' => '1400000144',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            106 => [
                'MAIL' => 'compostura@opensports.com.ar',
                'NOMBRE' => 'Pablo',
                'APELLIDO' => 'Damianovich',
                'NOMBRE_CLIENTE' => 'STADIO UNO TRIP',
                'SO' => '1400000145',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            107 => [
                'MAIL' => 'compostura@opensports.com.ar',
                'NOMBRE' => 'Pablo',
                'APELLIDO' => 'Damianovich',
                'NOMBRE_CLIENTE' => 'STADIO UNO OPEN',
                'SO' => '1400000127',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            108 => [
                'MAIL' => 'compostura@opensports.com.ar',
                'NOMBRE' => 'Pablo',
                'APELLIDO' => 'Damianovich',
                'NOMBRE_CLIENTE' => 'MDQ LE SPORT S.A.',
                'SO' => '1400000201',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            109 => [
                'MAIL' => 'compostura@opensports.com.ar',
                'NOMBRE' => 'Pablo',
                'APELLIDO' => 'Damianovich',
                'NOMBRE_CLIENTE' => 'MDQ LE SPORT S.A. GuEMES AS',
                'SO' => '1400000202',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            110 => [
                'MAIL' => 'compostura@opensports.com.ar',
                'NOMBRE' => 'Pablo',
                'APELLIDO' => 'Damianovich',
                'NOMBRE_CLIENTE' => 'MDQ LE SPORT S.A. L1',
                'SO' => '1400000203',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            111 => [
                'MAIL' => 'noelia.duberti@luquin.com.ar',
                'NOMBRE' => 'Noelia',
                'APELLIDO' => 'Duberti',
                'NOMBRE_CLIENTE' => 'ANTONIO LUQUIN S.A.',
                'SO' => '1400000146',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            112 => [
                'MAIL' => 'noelia.duberti@luquin.com.ar',
                'NOMBRE' => 'Noelia',
                'APELLIDO' => 'Duberti',
                'NOMBRE_CLIENTE' => 'LUQUIN BEST AS',
                'SO' => '1400000147',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            113 => [
                'MAIL' => 'noelia.duberti@luquin.com.ar',
                'NOMBRE' => 'Noelia',
                'APELLIDO' => 'Duberti',
                'NOMBRE_CLIENTE' => 'ANTONIO LUQUIN S.A. NS Tucuman',
                'SO' => '1400000193',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            114 => [
                'MAIL' => 'noelia.duberti@luquin.com.ar',
                'NOMBRE' => 'Noelia',
                'APELLIDO' => 'Duberti',
                'NOMBRE_CLIENTE' => 'ANTONIO LUQUIN S.A.',
                'SO' => '1400000416',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            115 => [
                'MAIL' => 'noelia.duberti@luquin.com.ar',
                'NOMBRE' => 'Noelia',
                'APELLIDO' => 'Duberti',
                'NOMBRE_CLIENTE' => 'ANTONIO LUQUIN S.A.',
                'SO' => '1400000424',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            116 => [
                'MAIL' => 'noelia.duberti@luquin.com.ar',
                'NOMBRE' => 'Noelia',
                'APELLIDO' => 'Duberti',
                'NOMBRE_CLIENTE' => 'ANTONIO LUQUIN S.A.',
                'SO' => '1400000425',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            117 => [
                'MAIL' => 'noelia.duberti@luquin.com.ar',
                'NOMBRE' => 'Noelia',
                'APELLIDO' => 'Duberti',
                'NOMBRE_CLIENTE' => 'ANTONIO LUQUIN S.A.',
                'SO' => '1400000426',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            118 => [
                'MAIL' => 'garantias@authogar.com',
                'NOMBRE' => 'Marina',
                'APELLIDO' => 'Muelas',
                'NOMBRE_CLIENTE' => 'CASIMIRO FELIX TOYOS',
                'SO' => '1400000149',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            119 => [
                'MAIL' => 'garantias@authogar.com',
                'NOMBRE' => 'Marina',
                'APELLIDO' => 'Muelas',
                'NOMBRE_CLIENTE' => 'CASIMIRO FELIX TOYOS SANTA OLA',
                'SO' => '1400000150',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            120 => [
                'MAIL' => 'soleallende.nike@gmail.com',
                'NOMBRE' => 'Zaira Soledad',
                'APELLIDO' => 'Allende',
                'NOMBRE_CLIENTE' => 'DEPORTES PEnA CORDOBA',
                'SO' => '1400000151',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            121 => [
                'MAIL' => 'soleallende.nike@gmail.com',
                'NOMBRE' => 'Zaira Soledad',
                'APELLIDO' => 'Allende',
                'NOMBRE_CLIENTE' => 'DEPORTES PEnA SANTA FE',
                'SO' => '1400000152',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            122 => [
                'MAIL' => 'calzado@ferracioli.com.ar',
                'NOMBRE' => 'Rodrigo angel',
                'APELLIDO' => 'Giacaman',
                'NOMBRE_CLIENTE' => 'CASA FERRACIOLI',
                'SO' => '1400000156',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            123 => [
                'MAIL' => 'richieri@ferracioli.com.ar',
                'NOMBRE' => 'Rodrigo angel',
                'APELLIDO' => 'Giacaman',
                'NOMBRE_CLIENTE' => 'CASA FERRACIOLI',
                'SO' => '1400000156',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            124 => [
                'MAIL' => 'administracion@hanssachs.com.ar',
                'NOMBRE' => 'Oscar',
                'APELLIDO' => 'Manduca',
                'NOMBRE_CLIENTE' => 'HANSSACHS',
                'SO' => '1400000157',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            125 => [
                'MAIL' => 'administracion@hanssachs.com.ar',
                'NOMBRE' => 'Oscar',
                'APELLIDO' => 'Manduca',
                'NOMBRE_CLIENTE' => 'VIEGAS',
                'SO' => '1400000158',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            126 => [
                'MAIL' => 'manuel@totalsport.com.ar',
                'NOMBRE' => 'Manuel',
                'APELLIDO' => 'Gonzalez Vidal',
                'NOMBRE_CLIENTE' => 'TOTAL SPORT 6DIEZ',
                'SO' => '1400000162',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            127 => [
                'MAIL' => 'reclamosnewsport@gmail.com',
                'NOMBRE' => 'Julian',
                'APELLIDO' => 'Lopez',
                'NOMBRE_CLIENTE' => 'ADOLFO ZAKIAN S.A.',
                'SO' => '1400000164',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            128 => [
                'MAIL' => 'reclamosnewsport@gmail.com',
                'NOMBRE' => 'Julian',
                'APELLIDO' => 'Lopez',
                'NOMBRE_CLIENTE' => 'FUENCARRAL',
                'SO' => '1400000165',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            129 => [
                'MAIL' => 'reclamosnewsport@gmail.com',
                'NOMBRE' => 'Julian',
                'APELLIDO' => 'Lopez',
                'NOMBRE_CLIENTE' => 'ZETA 4 SB',
                'SO' => '1400000205',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            130 => [
                'MAIL' => 'reclamosnewsport@gmail.com',
                'NOMBRE' => 'Julian',
                'APELLIDO' => 'Lopez',
                'NOMBRE_CLIENTE' => 'ADOLFO ZAKIAN S.A. TEMPLO FUTBOL',
                'SO' => '1400000206',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            131 => [
                'MAIL' => 'reclamosnewsport@gmail.com',
                'NOMBRE' => 'Julian',
                'APELLIDO' => 'Lopez',
                'NOMBRE_CLIENTE' => 'ADOLFO ZAKIAN S.A.',
                'SO' => '1400000417',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            132 => [
                'MAIL' => 'devoluciones@sport78.com.ar',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'GRAELLS DIONYSOS BS AS',
                'SO' => '1400000166',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            133 => [
                'MAIL' => 'devoluciones@sport78.com.ar',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'DIONYSOS',
                'SO' => '1400000418',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            134 => [
                'MAIL' => 'devoluciones@sport78.com.ar',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'GRAELLS NELSON A. SPORT 78',
                'SO' => '1400000419',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            135 => [
                'MAIL' => 'devoluciones@sport78.com.ar',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'GRAELLS NELSON A. SPORT 78',
                'SO' => '1400000420',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            136 => [
                'MAIL' => 'devoluciones@sport78.com.ar',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'GRAELLS NELSON A. SPORT 78',
                'SO' => '1400000427',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            137 => [
                'MAIL' => 'devoluciones@sport78.com.ar',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'GRAELLS NELSON A. SPORT 78',
                'SO' => '1400000428',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            138 => [
                'MAIL' => 'devoluciones@sport78.com.ar',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'BLAST AS D',
                'SO' => '1400000429',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            139 => [
                'MAIL' => 'devoluciones@sport78.com.ar',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'GRAELLS NELSON A. SPORT 78',
                'SO' => '1400000421',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            140 => [
                'MAIL' => 'devoluciones@sport78.com.ar',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'GRAELLS NELSON A. Nike Shop',
                'SO' => '1400000194',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            141 => [
                'MAIL' => 'devoluciones@sport78.com.ar',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'GRAELLS NELSON A.NS ALTO ROSARIO',
                'SO' => '1400000195',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            142 => [
                'MAIL' => 'devoluciones@sport78.com.ar',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'DIONYSOS',
                'SO' => '1400000207',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            143 => [
                'MAIL' => 'devoluciones@sport78.com.ar',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'FLUID',
                'SO' => '1400000208',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            144 => [
                'MAIL' => 'devoluciones@sport78.com.ar',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'GRAELLS NELSON A.L2 PORTAL SHOPP',
                'SO' => '1400000209',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            145 => [
                'MAIL' => 'devoluciones@sport78.com.ar',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'GRAELLS NELSON A.BLAST AS ALTO ROS',
                'SO' => '1400000210',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            146 => [
                'MAIL' => 'andrea.piunti@solodeportes.com',
                'NOMBRE' => 'Andrea',
                'APELLIDO' => 'Piunti',
                'NOMBRE_CLIENTE' => 'BLOISE Hnos.Soc.de H.',
                'SO' => '1400000167',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            147 => [
                'MAIL' => 'fallas@rossettideportes.com',
                'NOMBRE' => 'Alejandro',
                'APELLIDO' => 'Cisana',
                'NOMBRE_CLIENTE' => 'CARLOS ROSSETTI S.A. - NS - NC',
                'SO' => '1400000196',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            148 => [
                'MAIL' => 'fallas@rossettideportes.com',
                'NOMBRE' => 'Alejandro',
                'APELLIDO' => 'Cisana',
                'NOMBRE_CLIENTE' => 'CARLOS ROSSETTI S.A.',
                'SO' => '1400000168',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            149 => [
                'MAIL' => 'fallas@rossettideportes.com',
                'NOMBRE' => 'Alejandro',
                'APELLIDO' => 'Cisana',
                'NOMBRE_CLIENTE' => 'CARLOS ROSSETTI S.A. AS - V.MARIA',
                'SO' => '1400000215',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            150 => [
                'MAIL' => 'fallas@rossettideportes.com',
                'NOMBRE' => 'Alejandro',
                'APELLIDO' => 'Cisana',
                'NOMBRE_CLIENTE' => 'CARLOS ROSSETTI S.A.',
                'SO' => '1400000422',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            151 => [
                'MAIL' => 'fallas@rossettideportes.com',
                'NOMBRE' => 'Alejandro',
                'APELLIDO' => 'Cisana',
                'NOMBRE_CLIENTE' => 'CARLOS ROSSETTI S.A.',
                'SO' => '1400000423',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            152 => [
                'MAIL' => 'emiliano.a@megasp.com.ar',
                'NOMBRE' => 'Emiliano',
                'APELLIDO' => 'Awad',
                'NOMBRE_CLIENTE' => 'CARJUL S.A.',
                'SO' => '1400000170',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            153 => [
                'MAIL' => 'emiliano.a@megasp.com.ar',
                'NOMBRE' => 'Emiliano',
                'APELLIDO' => 'Awad',
                'NOMBRE_CLIENTE' => 'CARJUL SA BETTER',
                'SO' => '1400000171',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            154 => [
                'MAIL' => 'emiliano.a@megasp.com.ar',
                'NOMBRE' => 'Emiliano',
                'APELLIDO' => 'Awad',
                'NOMBRE_CLIENTE' => 'SPORTS LIFE SA',
                'SO' => '1400000185',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            155 => [
                'MAIL' => 'mvico@deporjean.com',
                'NOMBRE' => 'Matias',
                'APELLIDO' => 'Vico',
                'NOMBRE_CLIENTE' => 'DEPOR JEAN DIGITAL',
                'SO' => '1400000174',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            156 => [
                'MAIL' => 'mvico@deporjean.com',
                'NOMBRE' => 'Matias',
                'APELLIDO' => 'Vico',
                'NOMBRE_CLIENTE' => 'DEPOR JEAN L2 ESQUINA STA FE',
                'SO' => '1400000175',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            157 => [
                'MAIL' => 'mvico@deporjean.com',
                'NOMBRE' => 'Matias',
                'APELLIDO' => 'Vico',
                'NOMBRE_CLIENTE' => 'DEPOR JEAN L2 PARANA',
                'SO' => '1400000176',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            158 => [
                'MAIL' => 'mvico@deporjean.com',
                'NOMBRE' => 'Matias',
                'APELLIDO' => 'Vico',
                'NOMBRE_CLIENTE' => 'DEPOR JEAN L2 SANTA FE',
                'SO' => '1400000177',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            159 => [
                'MAIL' => 'mvico@deporjean.com',
                'NOMBRE' => 'Matias',
                'APELLIDO' => 'Vico',
                'NOMBRE_CLIENTE' => 'DEPOR JEAN RUSH TOWN',
                'SO' => '1400000178',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            160 => [
                'MAIL' => 'mvico@deporjean.com',
                'NOMBRE' => 'Matias',
                'APELLIDO' => 'Vico',
                'NOMBRE_CLIENTE' => 'DEPOR JEAN S.A.',
                'SO' => '1400000179',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            161 => [
                'MAIL' => 'miribas@deporjean.com',
                'NOMBRE' => 'Marcelo',
                'APELLIDO' => 'Iribas',
                'NOMBRE_CLIENTE' => 'DEPOR JEAN DIGITAL',
                'SO' => '1400000174',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            162 => [
                'MAIL' => 'miribas@deporjean.com',
                'NOMBRE' => 'Marcelo',
                'APELLIDO' => 'Iribas',
                'NOMBRE_CLIENTE' => 'DEPOR JEAN L2 ESQUINA STA FE',
                'SO' => '1400000175',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            163 => [
                'MAIL' => 'miribas@deporjean.com',
                'NOMBRE' => 'Marcelo',
                'APELLIDO' => 'Iribas',
                'NOMBRE_CLIENTE' => 'DEPOR JEAN L2 PARANA',
                'SO' => '1400000176',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            164 => [
                'MAIL' => 'miribas@deporjean.com',
                'NOMBRE' => 'Marcelo',
                'APELLIDO' => 'Iribas',
                'NOMBRE_CLIENTE' => 'DEPOR JEAN L2 SANTA FE',
                'SO' => '1400000177',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            165 => [
                'MAIL' => 'miribas@deporjean.com',
                'NOMBRE' => 'Marcelo',
                'APELLIDO' => 'Iribas',
                'NOMBRE_CLIENTE' => 'DEPOR JEAN RUSH TOWN',
                'SO' => '1400000178',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            166 => [
                'MAIL' => 'miribas@deporjean.com',
                'NOMBRE' => 'Marcelo',
                'APELLIDO' => 'Iribas',
                'NOMBRE_CLIENTE' => 'DEPOR JEAN S.A.',
                'SO' => '1400000179',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            167 => [
                'MAIL' => 'devolucionafabrica@deporjean.com',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'DEPOR JEAN DIGITAL',
                'SO' => '1400000174',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            168 => [
                'MAIL' => 'devolucionafabrica@deporjean.com',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'DEPOR JEAN L2 ESQUINA STA FE',
                'SO' => '1400000175',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            169 => [
                'MAIL' => 'devolucionafabrica@deporjean.com',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'DEPOR JEAN L2 PARANA',
                'SO' => '1400000176',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            170 => [
                'MAIL' => 'devolucionafabrica@deporjean.com',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'DEPOR JEAN L2 SANTA FE',
                'SO' => '1400000177',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            171 => [
                'MAIL' => 'devolucionafabrica@deporjean.com',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'DEPOR JEAN RUSH TOWN',
                'SO' => '1400000178',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            172 => [
                'MAIL' => 'devolucionafabrica@deporjean.com',
                'NOMBRE' => '',
                'APELLIDO' => '',
                'NOMBRE_CLIENTE' => 'DEPOR JEAN S.A.',
                'SO' => '1400000179',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            173 => [
                'MAIL' => 'francisco.garcia@pacogarcia.com.ar',
                'NOMBRE' => 'Francisco',
                'APELLIDO' => 'Garcia',
                'NOMBRE_CLIENTE' => 'PACO GARCIA S.A.',
                'SO' => '1400000182',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            174 => [
                'MAIL' => 'francisco.garcia@pacogarcia.com.ar',
                'NOMBRE' => 'Francisco',
                'APELLIDO' => 'Garcia',
                'NOMBRE_CLIENTE' => 'PACO GARCIA SA L2',
                'SO' => '1400000183',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            175 => [
                'MAIL' => 'carlos.parodi@valenet.com.ar',
                'NOMBRE' => 'Carlos',
                'APELLIDO' => 'Parodi',
                'NOMBRE_CLIENTE' => 'TESI S.A.',
                'SO' => '1400000186',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            176 => [
                'MAIL' => 'carlos.parodi@valenet.com.ar',
                'NOMBRE' => 'Carlos',
                'APELLIDO' => 'Parodi',
                'NOMBRE_CLIENTE' => 'TESI S.A. MENDOZA',
                'SO' => '1400000187',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            177 => [
                'MAIL' => 'carlos.parodi@valenet.com.ar',
                'NOMBRE' => 'Carlos',
                'APELLIDO' => 'Parodi',
                'NOMBRE_CLIENTE' => 'TESI S.A. SAN JUAN',
                'SO' => '1400000188',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            178 => [
                'MAIL' => 'Garantias@dash-deportes.com.ar',
                'NOMBRE' => 'Pablo',
                'APELLIDO' => 'Velardez',
                'NOMBRE_CLIENTE' => 'AMI MUSIC S.A.',
                'SO' => '1400000197',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            179 => [
                'MAIL' => 'Garantias@dash-deportes.com.ar',
                'NOMBRE' => 'Pablo',
                'APELLIDO' => 'Velardez',
                'NOMBRE_CLIENTE' => 'ESSENTIAL S.A.',
                'SO' => '1400000198',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            180 => [
                'MAIL' => 'Garantias@dash-deportes.com.ar',
                'NOMBRE' => 'Pablo',
                'APELLIDO' => 'Velardez',
                'NOMBRE_CLIENTE' => 'ESSENTIAL S.A. MARK',
                'SO' => '1400000199',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            181 => [
                'MAIL' => 'Garantias@dash-deportes.com.ar',
                'NOMBRE' => 'Pablo',
                'APELLIDO' => 'Velardez',
                'NOMBRE_CLIENTE' => 'ANNEX S.A. CSW',
                'SO' => '1400000200',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            182 => [
                'MAIL' => 'reparaciones@sportline.com.ar',
                'NOMBRE' => 'Diego',
                'APELLIDO' => 'Montiel',
                'NOMBRE_CLIENTE' => 'ISRAEL FELER S.A.',
                'SO' => '1400000211',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            183 => [
                'MAIL' => 'garantias@showsport.com.ar',
                'NOMBRE' => 'Miguel Angel',
                'APELLIDO' => 'Sanchez',
                'NOMBRE_CLIENTE' => 'KADIMA S.A.',
                'SO' => '1400000212',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            184 => [
                'MAIL' => 'garantias@mateu.com.ar',
                'NOMBRE' => 'Fabian',
                'APELLIDO' => 'Guida',
                'NOMBRE_CLIENTE' => 'MATEU SPORTS',
                'SO' => '1400000213',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            185 => [
                'MAIL' => 'garantias@mateu.com.ar',
                'NOMBRE' => 'Fabian',
                'APELLIDO' => 'Guida',
                'NOMBRE_CLIENTE' => 'MATEU SPORTS AURELIUS',
                'SO' => '1400000214',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            186 => [
                'MAIL' => 'k.superfutbol@gmail.com',
                'NOMBRE' => 'Kevin',
                'APELLIDO' => 'Echt',
                'NOMBRE_CLIENTE' => 'SUPERFUTBOL SRL',
                'SO' => '1400000216',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ],
            187 => [
                'MAIL' => 'Julian.Luongo@torneos.com',
                'NOMBRE' => 'Julian',
                'APELLIDO' => 'Luongo',
                'NOMBRE_CLIENTE' => 'TORNEOS Y COMPETENCIAS S.A.',
                'SO' => '1400000217',
                'PAIS' => 'ARG',
                'ROL' => 'Cliente',
                'MONTO A APROBAR' => '',
            ]
        ];
            return $data;
    }

}
