<?php
// phpcs:disable Magento2.Templates.ThisInTemplate
// @codingStandardsIgnoreFile

/** @var Magento\Sales\Block\Order\History $block */
?>
<?php $_orders = $block->getOrders(); ?>
<?= $block->getChildHtml('info') ?>
<?php if ($_orders && count($_orders)) : ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?= $block->escapeHtml(__('Orders')) ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col id"><?= $block->escapeHtml(__('Order #')) ?></th>
                <th scope="col" class="col date"><?= $block->escapeHtml(__('Date')) ?></th>
                <th scope="col" class="col shipping"><?= $block->escapeHtml(__('Ship To')) ?></th>
                <?= $block->getChildHtml('extra.column.header') ?>
                <th scope="col" class="col total"><?= $block->escapeHtml(__('Order Total')) ?></th>
                <th scope="col" class="col total-qty-ordered"><?= $block->escapeHtml(__('Items Ordered')) ?></th>
                <th scope="col" class="col status"><?= $block->escapeHtml(__('Status')) ?></th>
                <th scope="col" class="col shipping"><?= $block->escapeHtml(__('Address')) ?></th>
                <th scope="col" class="col actions"><?= $block->escapeHtml(__('Action')) ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($_orders as $_order) : ?>
                <tr>
                    <td data-th="<?= $block->escapeHtml(__('Order #')) ?>" class="col id"><?= $block->escapeHtml($_order->getRealOrderId()) ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Date')) ?>" class="col date"><?= /* @noEscape */ $block->formatDate($_order->getCreatedAt()) ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Ship To')) ?>" class="col shipping"><?= $_order->getShippingAddress() ? $block->escapeHtml($block->getShipToName($_order->getShippingAddress()->getVatId())) : "&nbsp;" ?></td>
                    <?php $extra = $block->getChildBlock('extra.container'); ?>
                    <?php if ($extra) : ?>
                        <?php $extra->setOrder($_order); ?>
                        <?= $extra->getChildHtml() ?>
                    <?php endif; ?>
                    <td data-th="<?= $block->escapeHtml(__('Order Total')) ?>" class="col total"><?= /* @noEscape */ $_order->formatPrice($_order->getGrandTotal()) ?></td>
                    <td data-th="<?= $block->escapeHtml(__('total-qty-ordered')) ?>" class="total-qty-ordered"><?= $block->escapeHtml((int)$_order->getTotalQtyOrdered()) ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Status')) ?>" class="col status"><?= $block->escapeHtml($_order->getStatusLabel()) ?></td>
                    <?php
                    $shippingAddress = $_order->getShippingAddress();
                    if ($shippingAddress !== null) {
                        $address = '';
//                        $region = $shippingAddress->getRegion() ?? '';
//                        $city = $shippingAddress->getCity() ?? '';
                        $street = $shippingAddress->getStreet();
                        $street1 = $street[0] ?? '';
                        $street2 = $street[1] ?? '';

//                        $address .= $block->escapeHtml($region . ', ');
//                        $address .= $block->escapeHtml($city . ', ');
                        $address .= $block->escapeHtml($street1 . ' ');
                        $address .= $block->escapeHtml($street2);
                        $address = mb_substr($address, 0, 80);
                    } else {
                        $address = '';
                    }
                    ?>
                    <td data-th="<?= $block->escapeHtml(__('Address')) ?>" class="col shipping"><?= $block->escapeHtml($address) ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
                        <a href="<?= $block->escapeUrl($block->getViewUrl($_order)) ?>" class="action view">
                            <span><?= $block->escapeHtml(__('View Order')) ?></span>
                        </a>
                        <?php
                        // Verificar si la orden es de los últimos 14 días para permitir el reorder
                        $canReorder = strtotime($_order->getCreatedAt()) >= strtotime('-14 days');
                        if ($canReorder && $this->helper(\Magento\Sales\Helper\Reorder::class)->canReorder($_order->getEntityId())) : ?>
                                  <a href="#" data-order-id="<?= $_order->getEntityId() ?>" class="action reorder">
                                <span><?= $block->escapeHtml(__('Reorder')) ?></span>
                            </a>
                        <?php endif ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()) : ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else : ?>
    <div class="message info empty"><span><?= $block->escapeHtml($block->getEmptyOrdersMessage()) ?></span></div>
<?php endif ?>


<script type="application/javascript">
    require(['jquery', 'ko', 'uiRegistry'],
        function ($, ko, registry) {
            $('.reorder').on('click', function (e) {
                e.preventDefault();

                var orderId = $(this).data('order-id');

                $('body').trigger('processStart');

                setTimeout(function () {
                    $.ajax({
                        url: '<?= $block->getUrl("sales/order/reorder") ?>order_id/' + orderId,
                        type: 'POST',
                        async: false,
                        success: function () {
                            window.location.href = '<?= $block->getUrl("checkout/cart/index") ?>';
                        },
                        error: function (xhr, status, error) {
                            console.error("Error al realizar reorder:", error);
                        },
                        complete: function () {
                            setTimeout(function () {
                                $('body').trigger('processStop')
                            }, 2000);
                        }
                    });
                }, 500);
            });
        }
    );
</script>
